// Package entity defines the core data structures for the RAG (Retrieval-Augmented Generation) system.
// This package provides entities for managing training documents, document chunks, and RAG queries/responses.
package entity

import "time"

// DocumentType represents the type of content in a training document.
// This enum is used to determine how content should be processed and chunked.
type DocumentType string

const (
	// DocumentTypeText represents plain text documents with standard chunking (500 chars)
	DocumentTypeText DocumentType = "text"
	// DocumentTypeAudio represents audio files that have been transcribed to text (600 char chunks)
	DocumentTypeAudio DocumentType = "audio"
	// DocumentTypeVideo represents video files that have been transcribed to text (600 char chunks)
	DocumentTypeVideo DocumentType = "video"
	// DocumentTypePDF represents PDF documents with larger chunks (800 chars)
	DocumentTypePDF DocumentType = "pdf"
	// DocumentTypeFAQ represents FAQ content processed as Q&A pairs
	DocumentTypeFAQ DocumentType = "faq"
	// DocumentTypeImage represents images with OCR text or descriptions (single chunk)
	DocumentTypeImage DocumentType = "image"
)

// TrainingDocument represents a document used to train an AI agent.
// Each document belongs to a specific agent and contains metadata about the source content.
// Documents are processed into chunks for vector embedding and retrieval.
type TrainingDocument struct {
	// ID is the unique identifier for the training document
	ID string `json:"id" gorm:"primaryKey;type:varchar(36)"`
	// AgentID links this document to a specific agent
	AgentID string `json:"agent_id" gorm:"type:varchar(36);not null;index"`
	// Title is a human-readable name for the document
	Title string `json:"title" gorm:"type:varchar(255);not null"`
	// DocumentType determines how the content is processed and chunked
	DocumentType DocumentType `json:"document_type" gorm:"type:varchar(20);not null;index"`
	// SourceURL is the original location of the document (optional)
	SourceURL *string `json:"source_url" gorm:"type:text"`
	// FileSize is the size of the original file in bytes (optional)
	FileSize *int64 `json:"file_size" gorm:"type:bigint"`
	// MimeType is the MIME type of the original file (optional)
	MimeType *string `json:"mime_type" gorm:"type:varchar(100)"`
	// IsActive determines if this document should be included in RAG queries
	IsActive bool `json:"is_active" gorm:"type:boolean;default:true;index"`
	// ProcessedAt timestamp when the document was successfully processed into chunks
	ProcessedAt *time.Time `json:"processed_at" gorm:"type:timestamp"`
	// CreatedAt timestamp when the document record was created
	CreatedAt time.Time `json:"created_at" gorm:"not null"`
	// UpdatedAt timestamp when the document record was last modified
	UpdatedAt time.Time `json:"updated_at" gorm:"not null"`
	// Agent is the associated agent (loaded via foreign key)
	Agent *Agent `json:"agent,omitempty" gorm:"foreignKey:AgentID;constraint:OnDelete:CASCADE;"`
	// Chunks are the processed text chunks from this document (loaded via foreign key)
	Chunks []DocumentChunk `json:"chunks,omitempty" gorm:"foreignKey:DocumentID;constraint:OnDelete:CASCADE;"`
}

// DocumentChunk represents a processed piece of text from a training document.
// Each chunk contains embeddings for semantic search and retrieval.
type DocumentChunk struct {
	// ID is the unique identifier for the chunk
	ID string `json:"id" gorm:"primaryKey;type:varchar(36)"`
	// DocumentID links this chunk to its parent training document
	DocumentID string `json:"document_id" gorm:"type:varchar(36);not null;index"`
	// AgentID links this chunk to the agent (denormalized for query performance)
	AgentID string `json:"agent_id" gorm:"type:varchar(36);not null;index"`
	// Content is the actual text content of this chunk
	Content string `json:"content" gorm:"type:text;not null"`
	// ChunkIndex is the sequential position of this chunk within the document
	ChunkIndex int `json:"chunk_index" gorm:"type:int;not null"`
	// Metadata contains additional information about the chunk (type, title, source, etc.)
	Metadata map[string]string `json:"metadata" gorm:"type:jsonb"`
	// Embedding is the vector representation generated by Cohere (1024 dimensions)
	Embedding []float32 `json:"-" gorm:"type:vector(1024)"`
	// CreatedAt timestamp when the chunk was created
	CreatedAt time.Time `json:"created_at" gorm:"not null"`
	// UpdatedAt timestamp when the chunk was last modified
	UpdatedAt time.Time `json:"updated_at" gorm:"not null"`
	// Document is the parent training document (loaded via foreign key)
	Document *TrainingDocument `json:"document,omitempty" gorm:"foreignKey:DocumentID;constraint:OnDelete:CASCADE;"`
	// Agent is the associated agent (loaded via foreign key)
	Agent *Agent `json:"agent,omitempty" gorm:"foreignKey:AgentID;constraint:OnDelete:CASCADE;"`
}

// TableName returns the database table name for TrainingDocument
func (TrainingDocument) TableName() string {
	return "training_documents"
}

// TableName returns the database table name for DocumentChunk
func (DocumentChunk) TableName() string {
	return "document_chunks"
}

// RAGQuery represents a request to retrieve relevant context for a user query.
// This is used to search through an agent's training documents for relevant information.
type RAGQuery struct {
	// Query is the user's question or search text
	Query string `json:"query"`
	// AgentID specifies which agent's knowledge base to search
	AgentID string `json:"agent_id"`
	// TopK is the maximum number of chunks to retrieve (default: 5)
	TopK int `json:"top_k,omitempty"`
	// Threshold is the minimum similarity score for results (default: 0.7)
	Threshold float32 `json:"threshold,omitempty"`
}

// RAGResponse contains the retrieved context and chunks for a RAG query.
// This provides both the combined context for LLM prompts and individual chunks for reference.
type RAGResponse struct {
	// Context is the combined text from all retrieved chunks, ready for LLM prompts
	Context string `json:"context"`
	// Chunks are the individual retrieved chunks with metadata and scores
	Chunks []RetrievedChunk `json:"chunks"`
	// Query is the original search query for reference
	Query string `json:"query"`
}

// RetrievedChunk represents a single chunk returned from a similarity search.
// It includes the content, metadata, similarity score, and source document information.
type RetrievedChunk struct {
	// Content is the text content of the retrieved chunk
	Content string `json:"content"`
	// Metadata contains additional information about the chunk (type, title, source, etc.)
	Metadata map[string]string `json:"metadata"`
	// Score is the similarity score between the query and this chunk (0.0 to 1.0)
	Score float32 `json:"score"`
	// DocumentID is the ID of the source training document
	DocumentID string `json:"document_id"`
	// DocumentType indicates the type of source document (text, pdf, audio, etc.)
	DocumentType DocumentType `json:"document_type"`
}
